SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [AutoWho].[CollectorOptFakeout](
	[ZeroOrOne] [bit] NOT NULL
) ON [PRIMARY]

GO
CREATE CLUSTERED INDEX [UCL1] ON [AutoWho].[CollectorOptFakeout]
(
	[ZeroOrOne] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
